### ISSUE TITLE
Duplicate Node entities

### ISSUE THREAD

**Issue by itchannel** [itchannel/tdarr_ha#13]
In certain circumstances HA creates a new sensor everytime a node reconnects!. Need to debug.

**Comment by wraith1385** [comment]
Came here to report this issue.  I have a Tdarr server and node installed on a M2 Mac Mini.  Let me know if you need anyone to test anything.

**Comment by itchannel** [comment]
@wraith1385 Out of interest are your nodes offline for a while before you reconnect. I'm wondering if the unique ID that was introduced in the latest Tdarr version changes after a while of the node being offline.

**Comment by wraith1385** [comment]
No, I was doing testing so the node was only offline for 15-60 seconds at a time.

**Comment by itchannel** [comment]
After doing some testing it looks like Tdarr generates a random SessionID and nodeID everytime you start the "Tdarr_Node.exe" and doesn't use the NodeID specified in the node_config file. 

```
"entity_id": "sensor.tdarr_node_stevepc",
"unique_id": "10.11.0.59-tdarr_node__NbH6h7C3",

"entity_id": "sensor.tdarr_node_stevepc_2",
"unique_id": "10.11.0.59-tdarr_node_QmSshz91w",

"entity_id": "sensor.tdarr_node_stevepc_3"
"unique_id": "10.11.0.59-tdarr_node_iBfJyl_G-",",

"entity_id": "sensor.tdarr_node_stevepc_4",
"unique_id": "10.11.0.59-tdarr_node_CPhu9d18a",
```

I'm going to the let the Tdarr Dev know, but for now I'll change the integration to just the Node Name. This could result in an error if someone has 2 nodes named exactly the same but it will at least inform the user.

**Comment by itchannel** [comment]
1.10 Fixes this issue 👍
