### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by Bovive** [itchannel/tdarr_ha#3]
I am able to add a tdarr server running on another computer (Windows 10) on the same network. When I try to add the locally hosted Tdarr server (Ubuntu) it cannot find it. The port is correct. I have tried localhost, 127.0.0.1, 0.0.0.0 and the local IP for the machine. This is my error log:

`This error originated from a custom integration.

Logger: custom_components.tdarr.config_flow
Source: custom_components/tdarr/config_flow.py:59
Integration: Tdarr (documentation, issues)
First occurred: 11:49:18 PM (14 occurrences)
Last logged: 11:53:26 PM

Failed to authenticate with Tdarr Server`

Any help would be appreciated. Thanks!

**Comment by itchannel** [comment]
If you run wget or curl on that ubuntu machine does it allow you to resolve your tdarr server?

As I had a similar issue on mine where I couldn't access the tdarr server locally only from a remote machine and seemed to be a tdarr problem as I couldn't access it using my browser, wget or HA. Never found why but seemed to be a docker network issue I think. Will try later today again to verify.

**Comment by Bovive** [comment]
I'll run a CURL when I get home. I can say that I can use the browser for tdarr locally on that machine. Also my Uptime Kuma sees it as online, which is hosted on the same machine and checking it as localhost. I don't use Docker. Thanks for helping me with it!

**Comment by itchannel** [comment]
How is your HA hosted? Docker, hassos or other?

**Comment by Bovive** [comment]
I have a core install on Ubuntu.

**Comment by Bovive** [comment]
It does appear that I receive a proper response from a CURL on the same machine using localhost. I tried the integration again and this time it worked. Not sure what was different. Thanks for your help!

**Comment by itchannel** [comment]
Glad it worked for you. I need to add some better error handling anyway. So if you get any more errors or any requests let me know 👍
